import "@/app/_styles/globals.css"
import "@/app/_styles/icon.css"
import React from "react";

export const metadata = {
  title: 'Grocery Shop',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children:  React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
